# Generated by Django 2.2.6 on 2019-11-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='airport_city',
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.City'),
            preserve_default=False,
        ),
    ]
