# Generated by Django 2.2.6 on 2019-11-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191125_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight_start_time',
            new_name='flight_end_time',
        ),
    ]
