# Generated by Django 2.2.6 on 2019-11-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191125_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_month', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_days',
            field=models.ManyToManyField(to='home.Day'),
        ),
    ]
