# Generated by Django 2.2.6 on 2019-11-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191127_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_business_places',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_econom_places',
            field=models.IntegerField(default=60),
        ),
    ]
