# Generated by Django 2.2.6 on 2019-11-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191127_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_business_places',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='fligth_econom_places',
            field=models.IntegerField(default=60),
        ),
        migrations.DeleteModel(
            name='Places',
        ),
    ]
